#!/usr/bin/env node
// Regenerate src/lib/og-images.js from cards.mjs (single source of truth).
// Each route -> its card WebP + descriptive alt (the flattened headline).
// getOgImageUrl absolutizes to https://thunderbayai.com/... (OG images must be
// absolute for the FB scraper). Returns null for unmapped routes so the caller
// falls back to the site default (/og.png). Run after rendering/optimizing.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { CARDS, flattenHeadline } from './cards.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '../../src/lib/og-images.js');
const SITE = 'https://thunderbayai.com';
const DIR = '/tbai-og';

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const entries = CARDS.filter((c) => c.route !== '__default__')
  .map((c) => {
    const alt = `${flattenHeadline(c.lines)} | Thunder Bay AI`;
    return `  '${c.route}': { path: '${DIR}/${c.slug}.webp', alt: '${esc(alt)}' },`;
  }).join('\n');

const file = `// src/lib/og-images.js
// Centralized Open Graph image mapping for Thunder Bay AI.
// GENERATED by scripts/og/wire.mjs from scripts/og/cards.mjs — edit there, not here.

const SITE = '${SITE}';

export const ogImageMap = {
${entries}
};

// Normalize a route (trailing slash + query tolerant).
const norm = (routePath) => (routePath || '').split('?')[0].replace(/\\/$/, '') || '/';

// Absolute OG image URL for a route, or null if the route has no card
// (the caller then falls back to the site default og.png).
export const getOgImageUrl = (routePath) => {
  const c = ogImageMap[norm(routePath)];
  return c ? SITE + c.path : null;
};

// Alt text for the mapped card, or null.
export const getOgImageAlt = (routePath) => {
  const c = ogImageMap[norm(routePath)];
  return c ? c.alt : null;
};
`;

fs.writeFileSync(OUT, file);
console.log(`wrote ${OUT} (${CARDS.length - 1} routes)`);
