// src/lib/og-images.js
// Centralized Open Graph image mapping for Thunder Bay AI.
// GENERATED by scripts/og/wire.mjs from scripts/og/cards.mjs — edit there, not here.

const SITE = 'https://thunderbayai.com';

export const ogImageMap = {
  '/': { path: '/tbai-og/home.webp', alt: 'The AI signal for the Northwest. | Thunder Bay AI' },
  '/blog/openai-gpt-5-6-sol-terra-luna-northwestern-ontario-business': { path: '/tbai-og/openai-gpt-5-6-sol-terra-luna-northwestern-ontario-business.webp', alt: 'OpenAI\'s GPT-5.6 for your business. | Thunder Bay AI' },
  '/blog/which-ai-model-tier-small-business-northwestern-ontario': { path: '/tbai-og/which-ai-model-tier-small-business-northwestern-ontario.webp', alt: 'Which AI model should you use? | Thunder Bay AI' },
  '/blog/alberta-ai-code-audit-northwestern-ontario-government-lesson': { path: '/tbai-og/alberta-ai-code-audit-northwestern-ontario-government-lesson.webp', alt: '466M lines in 20 hours. | Thunder Bay AI' },
  '/blog/nohfc-workforce-development-internship-northern-ontario': { path: '/tbai-og/nohfc-workforce-development-internship-northern-ontario.webp', alt: '$35,000 for a tech intern. | Thunder Bay AI' },
  '/blog/nohfc-invest-north-innovation-rd-commercialization-northern-ontario': { path: '/tbai-og/nohfc-invest-north-innovation-rd-commercialization-northern-ontario.webp', alt: '$2 million for R&D. | Thunder Bay AI' },
  '/blog/signal-ai-funding-nwo-week-july-6-2026': { path: '/tbai-og/signal-ai-funding-nwo-week-july-6-2026.webp', alt: 'The Signal July 6. | Thunder Bay AI' },
  '/blog/nohfc-invest-north-grow-expansion-northern-ontario': { path: '/tbai-og/nohfc-invest-north-grow-expansion-northern-ontario.webp', alt: 'Grants + loans to expand. | Thunder Bay AI' },
  '/blog/claude-sonnet-5-cheaper-ai-agents-nwo-business': { path: '/tbai-og/claude-sonnet-5-cheaper-ai-agents-nwo-business.webp', alt: 'Sonnet 5 made cheaper agents. | Thunder Bay AI' },
  '/blog/nohfc-invest-north-launch-new-business-northern-ontario': { path: '/tbai-og/nohfc-invest-north-launch-new-business-northern-ontario.webp', alt: '$200,000 to start up. | Thunder Bay AI' },
  '/blog/canada-ai-for-all-strategy-nwo-business': { path: '/tbai-og/canada-ai-for-all-strategy-nwo-business.webp', alt: 'Canada\'s AI plan for the North. | Thunder Bay AI' },
  '/blog/fednor-rtri-tariff-response-northern-ontario': { path: '/tbai-og/fednor-rtri-tariff-response-northern-ontario.webp', alt: 'Up to $1M for tariff hits. | Thunder Bay AI' },
  '/blog/fednor-bsp-scale-up-productivity-northern-ontario': { path: '/tbai-og/fednor-bsp-scale-up-productivity-northern-ontario.webp', alt: 'Up to $500K to scale up. | Thunder Bay AI' },
  '/blog/signal-ai-funding-nwo-week-june-29-2026': { path: '/tbai-og/signal-ai-funding-nwo-week-june-29-2026.webp', alt: 'The Signal June 29. | Thunder Bay AI' },
  '/blog/signal-ai-funding-nwo-week-june-28-2026': { path: '/tbai-og/signal-ai-funding-nwo-week-june-28-2026.webp', alt: 'The Signal June 28. | Thunder Bay AI' },
  '/blog/ai-becoming-governed-fable-shutdown-canada': { path: '/tbai-og/ai-becoming-governed-fable-shutdown-canada.webp', alt: 'AI is now governed. | Thunder Bay AI' },
  '/blog/raii-vs-bbaa-which-grant-northwestern-ontario': { path: '/tbai-og/raii-vs-bbaa-which-grant-northwestern-ontario.webp', alt: 'RAII vs BBAA: which grant? | Thunder Bay AI' },
  '/blog/ai-for-thunder-bay-businesses-2026': { path: '/tbai-og/ai-for-thunder-bay-businesses-2026.webp', alt: 'AI in Thunder Bay, 2026. | Thunder Bay AI' },
  '/blog/chatgpt-vs-claude-canadian-small-business': { path: '/tbai-og/chatgpt-vs-claude-canadian-small-business.webp', alt: 'ChatGPT vs Claude for Canada. | Thunder Bay AI' },
  '/blog/openclaw-ai-agent-northwest-business': { path: '/tbai-og/openclaw-ai-agent-northwest-business.webp', alt: 'OpenClaw: the AI agent. | Thunder Bay AI' },
  '/blog/ai-in-google-workspace-northwest-business': { path: '/tbai-og/ai-in-google-workspace-northwest-business.webp', alt: 'AI is now in Workspace. | Thunder Bay AI' },
  '/blog/ai-agents-vs-chatbots-difference': { path: '/tbai-og/ai-agents-vs-chatbots-difference.webp', alt: 'Agents vs chatbots. | Thunder Bay AI' },
  '/blog/vibe-coding-what-it-means-for-business': { path: '/tbai-og/vibe-coding-what-it-means-for-business.webp', alt: 'Vibe coding explained. | Thunder Bay AI' },
  '/blog/ai-and-jobs-northwestern-ontario': { path: '/tbai-og/ai-and-jobs-northwestern-ontario.webp', alt: 'AI and jobs in the North. | Thunder Bay AI' },
  '/blog/ai-and-robotics-northern-industry': { path: '/tbai-og/ai-and-robotics-northern-industry.webp', alt: 'AI + robotics for industry. | Thunder Bay AI' },
  '/blog/bbaa-ai-adoption-grant-northwestern-ontario': { path: '/tbai-og/bbaa-ai-adoption-grant-northwestern-ontario.webp', alt: 'Up to $20K to adopt AI. | Thunder Bay AI' },
  '/blog/practical-ai-uses-nwo-business-this-quarter': { path: '/tbai-og/practical-ai-uses-nwo-business-this-quarter.webp', alt: 'Practical AI, this quarter. | Thunder Bay AI' },
  '/blog/choose-an-ai-model-without-the-hype': { path: '/tbai-og/choose-an-ai-model-without-the-hype.webp', alt: 'Pick an AI model, skip the hype. | Thunder Bay AI' },
  '/blog/ai-in-nwo-public-sector-where-it-fits': { path: '/tbai-og/ai-in-nwo-public-sector-where-it-fits.webp', alt: 'AI in the public sector. | Thunder Bay AI' },
  '/blog/fednor-raii-who-qualifies-thunder-bay': { path: '/tbai-og/fednor-raii-who-qualifies-thunder-bay.webp', alt: 'FedNor RAII: who qualifies? | Thunder Bay AI' },
  '/blog/noic-costarter-accelerator-readiness': { path: '/tbai-og/noic-costarter-accelerator-readiness.webp', alt: 'Costarter: the accelerator. | Thunder Bay AI' },
  '/blog/fund-a-custom-ai-build-with-a-grant': { path: '/tbai-og/fund-a-custom-ai-build-with-a-grant.webp', alt: 'Fund AI with a grant, not cash. | Thunder Bay AI' },
};

// Normalize a route (trailing slash + query tolerant).
const norm = (routePath) => (routePath || '').split('?')[0].replace(/\/$/, '') || '/';

// Absolute OG image URL for a route, or null if the route has no card
// (the caller then falls back to the site default og.png).
export const getOgImageUrl = (routePath) => {
  const c = ogImageMap[norm(routePath)];
  return c ? SITE + c.path : null;
};

// Alt text for the mapped card, or null.
export const getOgImageAlt = (routePath) => {
  const c = ogImageMap[norm(routePath)];
  return c ? c.alt : null;
};
